export type VocabStatus = 'new' | 'reviewing' | 'learned';
export type VocabTerm = { id:string; family:string; name:string; detail:string; cue:string; section:'Barre'|'Centre'|'Allegro'|'Pointe'; free?:'Focal'|'Linking' };

export const vocabulary: VocabTerm[] = [
  ['plies','Pliés','Demi-plié','In 1st, 2nd, 4th and 5th positions.','Bend over the toes; keep the heels grounded.','Barre'],
  ['grand-plies','Pliés','Grand plié','In 1st, 2nd and 5th positions.','Lift through the torso while the knees open over the toes.','Barre'],
  ['tendus','Battements tendus','Battement tendu','Devant, to 2nd and derrière from 5th in 2 counts.','Brush through the whole foot; close to a precise fifth.','Barre'],
  ['glisses','Battements glissés','Battement glissé','Devant, to 2nd and derrière from 5th; to 2nd from 1st.','Release just off the floor without lifting the hip.','Barre'],
  ['frappe','Battements frappés','Battement frappé to 2nd','A sharply struck extension to second.','The lower leg darts; the thigh stays quiet.','Barre'],
  ['petits-battements','Petits battements','Petit battement','Beating action sur le cou-de-pied.','Keep the knee open and articulate below it.','Barre'],
  ['rond-terre','Ronds de jambe','Rond de jambe à terre','Full and demi, en dehors and en dedans.','Draw the largest clean arc your pelvis can keep still.','Barre'],
  ['demi-grand-rond','Ronds de jambe','Demi grand rond de jambe','En dehors and en dedans.','Carry the leg evenly around the arc; do not hike the hip.','Barre'],
  ['developpe','Développés','Développé','Devant and to 2nd position.','Lift the knee first, then unfurl the lower leg.','Barre'],
  ['grand-battement','Grands battements','Grand battement','Devant, to 2nd and derrière.','Brush before you throw; control the return.','Barre'],
  ['grand-cloche','Grands battements','Grand battement en cloche','A continuous front-and-back swing through 1st.','The leg swings; the torso does not.','Barre'],
  ['arabesques','Arabesques','1st & 2nd arabesque','RAD lines distinguished by the relationship of the arms to the supporting leg.','Lengthen from fingertips through the back toes.','Centre'],
  ['body-poses','Poses of the body','Croisé & effacé','Devant and derrière.','Let the body diagonal make the line readable.','Centre'],
  ['balances','Balancés','Balancé de côté','A side-to-side waltz step.','Down–up–up: let the first step breathe.','Centre'],
  ['temps-lie','Temps liés','Basic temps lié','En avant and to 2nd.','Connect each transfer through the floor.','Centre'],
  ['weight-transfer','Transfers of weight','Full transfer of weight','Through 2nd; through 4th en avant and en arrière.','Arrive completely over the new supporting foot.','Centre'],
  ['pirouette-dehors','Pirouettes','Pirouette en dehors','Single from demi-plié in 4th position.','Push from both legs and close the ribs over the pelvis.','Centre'],
  ['pirouette-dedans','Pirouettes','Pirouette en dedans','Single from 4th position en fondu.','Turn toward the supporting leg; arrive before you descend.','Centre'],
  ['pose','Posés','Posé','En avant, en arrière and de côté; into arabesque or retiré.','Step onto a stretched leg and rise through the ankle.','Centre'],
  ['pas-valses','Pas de valses','Pas de valse en tournant','A turning waltz step.','Keep the three-count pulse buoyant and continuous.','Centre'],
  ['sautes','Sautés','Sauté','In 1st, 2nd and 4th position.','Land through toes–balls–heels into the next plié.','Allegro'],
  ['changements','Changements','Changement','By ¼ turn and battu.','Change the feet cleanly in the air; show fifth on landing.','Allegro','Linking'],
  ['echappe-saute','Échappés sautés','Échappé sauté','To 2nd; fermé from 2nd; changé; battu fermé.','Open and close symmetrically from the thighs.','Allegro'],
  ['glissade','Glissades','Glissade','Devant, derrière, dessus and dessous; running en avant and de côté.','Brush both feet and travel low, like skimming silk.','Allegro','Linking'],
  ['assemble','Assemblés','Assemblé','Devant, derrière, dessus and dessous.','Brush one leg, assemble both together in the air.','Allegro','Focal'],
  ['petit-assemble','Assemblés','Petit assemblé','Devant and derrière.','Small does not mean vague: beat the fifth cleanly.','Allegro','Linking'],
  ['sissonne','Sissonnes','Sissonne fermée de côté','Devant, derrière, dessus and dessous.','Two feet take off; one foot lands first, then close.','Allegro','Focal'],
  ['jete-ordinaire','Jetés','Jeté ordinaire','Devant and derrière.','Brush, spring, and land with the other foot at cou-de-pied.','Allegro','Focal'],
  ['jete-passe','Jetés','Jeté passé','Devant and derrière.','Pass the working leg crisply as the jump changes sides.','Allegro'],
  ['jete-attitude','Jetés','Jeté in petit attitude devant','A jeté finishing in low attitude devant.','Keep the thigh lifted and the lower leg softly curved.','Allegro'],
  ['grand-jete','Jetés','Grand jeté en avant','A travelling split leap forward.','Brush the front leg; project forward before opening the split.','Allegro'],
  ['pas-bourree','Pas de bourrées','Pas de bourrée','Devant, derrière, dessus and dessous.','Three tiny weight changes; know which foot finishes front.','Allegro','Linking'],
  ['coupe-chasse-pdb','Linking steps','Coupé chassé pas de bourrée','A prescribed linking phrase for free enchaînement.','Keep the feet speaking clearly while travelling.','Allegro','Linking'],
  ['temps-leve','Temps levés','Temps levé','In attitude, retiré and 1st or 2nd arabesque.','Spring from one foot and return through a cushioned landing.','Allegro','Linking'],
  ['pas-chat','Pas de chats','Pas de chat','A sideways jump passing both legs through retiré.','Lift each knee; keep the upper body serene.','Allegro'],
  ['soubresaut','Soubresauts','Soubresaut','A jump from two feet to two feet without changing.','Hold the fifth in the air and travel as one shape.','Allegro'],
  ['releve','Relevés','Relevé','In 1st, 2nd and 5th; devant, derrière and passé.','Plié, then rise sharply over stable toes.','Pointe'],
  ['rise','Rises','Rise','Onto demi-pointe in 1st, 2nd and 5th; pointe in 1st.','Rise with straight knees and control the descent.','Pointe'],
  ['echappe-releve','Échappés relevés','Échappé relevé changé','En demi-pointe and en pointe.','Open from fifth, change, and close through equal feet.','Pointe'],
  ['courus','Courus','Courus','En tournant, en demi-pointe and en demi-plié; sur place en pointe.','Use minute, even steps and keep the legs zipped together.','Pointe'],
  ['spring-points','Spring points','Spring points','Small springing actions through the pointe shoe.','Use the floor quickly without sitting into the supporting hip.','Pointe'],
].map(([id,family,name,detail,cue,section,free]) => ({id,family,name,detail,cue,section,free} as VocabTerm));

